### ISSUE TITLE
Run command in build file using Gradle

### ISSUE THREAD

**Issue by HieronyM** [jlouns/gradle-cross-platform-exec-plugin#3]
Thanks for the nice Feature,

btw, I have some problem when implement the command into my build file that use Gradle.
I make the task as below.

task lint (type : CrossPlatformExec, description : "Perform syntax check of sourcecode files"){
    commandLine '' "find . -name *.php -exec php -l "{}" \;"
}

But, It's give me an error like this:

build file 'C:\Users\intern\Desktop\gitlist-master\build.gradle': 40: unexpected char: '\' @ line 40, column 31.
commandLine '' "find . -name *.php -exec php -l "{}" \;"

Can you help me figured out what's wrong in the command?
Thanks.

**Comment by jlouns** [comment]
You have some issues with quotes and the backslash in your string. I think you want something like this:

``` gradle
task lint (type : CrossPlatformExec, description : "Perform syntax check of sourcecode files"){
  commandLine "find . -name *.php -exec php -l {} \\;"
}
```
