### ISSUE TITLE
Cross platform path support

### ISSUE THREAD

**Issue by denis-itskovich** [jlouns/gradle-cross-platform-exec-plugin#4]
There should be a cross-platform way to define `commandLine`, containing relative or absolute path. 

Problematic example: following configuration will return error, when running on Windows:

```
task bowerInstall(dependsOn: 'npmInstall', type: CrossPlatformExec) {
    workingDir "$project.projectDir/src/main/webapp"
    commandLine "./node_modules/.bin/bower", 'install'
}
```

I had to replace `/` with `\\` in `commadLine` option in order to run without errors:

```
task bowerInstall(dependsOn: 'npmInstall', type: CrossPlatformExec) {
    workingDir "$project.projectDir/src/main/webapp"
    commandLine ".\\node_modules\\.bin\\bower", 'install'
}
```

Notice, that `workingDir` seems working fine with unix-style path.

My suggestion is to convert unix-style paths to windows paths when running on windows host.

**Comment by jlouns** [comment]
Yeah, that's an issue. I'll work on it. I'd also accept a PR.
